services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=GO_USER_JWT
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminPassword

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"